### ISSUE TITLE
Tweet integration from tweets.json

### ISSUE THREAD

**Issue by yohann0412** [yohann0412/lumiAI#1]
@7erhii hey, need you to take the tweets from tweets.json located in root directory and load them as chat logs. its set to be arranged in reverse order of date already (so you don't need to do any sorting). just need you to get the content from each tweet and put it in as a log, and use the url to redirect (anchor tags) for the whole chat log. Don't copy paste the tweets since we're going to dynamically change tweets.json everytime a new tweet is made, so you'll have to reference it accordingly. lemme know if any questions. 
Thank you

**Comment by 7erhii** [comment]
Hello
Done
